runmode: debug                 # 开发模式, debug, release, test
port: 5080                  # HTTP绑定端口
name: goapi              # API Server的名字
httpurl: http://127.0.0.1:5080   # pingServer函数请求的API服务器的ip:port
tcpurl: 127.0.0.1:8888
max_ping_count: 10           # pingServer函数try的次数
idc: lf

discovery:
  name: zk
  server_name: my-app
  path: /root/lizongrong/service
  nodes: 127.0.0.1:1181,127.0.0.1:2181,127.0.0.1:3181
  updateinterval: 1e10

